### ISSUE TITLE
onGridRowsUpdated called twice on click away

### ISSUE THREAD

**Issue by scrambled2k3** [adazzle/react-data-grid#1061]
Bug report:

I have a grid cell that is editable and am relying on the 'onGridRowsUpdated' property to know when to save the updated field.  However, when I click away outside of the grid this property gets triggered twice instead of just once.

React Version: 15.6
Browser: Chrome

**Comment by qili26** [comment]
@scrambled2k3 
Though I think it should be fixed inside the grid, but you can have another work around by trying to use your own editor instead of the default one, the issue will be gone.

Further, I remember this issue happens only when you click outside of the table, if you click inside anywhere of the table the event is dispatched only once.

https://github.com/adazzle/react-data-grid/issues/880

**Comment by scrambled2k3** [comment]
@qili26, you are correct....it only fires once so long as you click somewhere else within the grid.

If it looks like this issue is not going to be easily resolved, I will look into that work-around.  Thank you for the suggestion.

**Comment by PhaniKumarAdiraju** [comment]
The issue is not resolved. It's triggering twice for me. Can you please re-open the issue?

**Comment by andrew-vogulkin** [comment]
Issue is actual, another way is adding event type to commit Event(or action), like a blurClick or change.
In this way anyone can handle event inside `onGridRowsUpdated`

**Comment by brakon** [comment]
Happens for me also

**Comment by mashaod** [comment]
I have the same issue. 
I see that editorProps.onBlur in this.createEditor has _this2.commit. //3680 string in react-data-grid.js
That's correct?
If I change it with this.handleBlur, then all is well.

**Comment by steamhammer** [comment]
Confirming the same incorrect behavior in `react-data-grid@6.1.0-0`.
As a workaround I'd suggest passing debounced fn as a `onGridRowsUpdated` callback.
https://github.com/adazzle/react-data-grid/issues/1452#issuecomment-478947865
