### ISSUE TITLE
Rows aren't load properly if scrolled down before changing columns

### ISSUE THREAD

**Issue by tihomir981** [adazzle/react-data-grid#1847]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes, there is an issue related to columns reordering (#1838) so just want to confirm I've already went through that one and it's not related.
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [X] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit a support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/docs/CONTRIBUTING.md

---

### Issue Details
Steps where it works properly:
1. Do not scroll below the initially loaded items of the table (related to minHeight, number of items etc. the table we have is loading 40k elements)
2. Change columns
3. Table appears as expected

Steps to reproduce the bug:
1. Scroll below the initially loaded items (3-4 screens).
2. Change columns
3. Table rows are not being loaded, until the user scrolls up or down. After scrolling up or down table loads rows as expected

Desired behavior here would be that it loads items right away instead of waiting for scroll event to happen in order to load the elements in the table. My assumption is that the issue is with the infinite scroll not checking on which section it is, after making changes to the columns table is loading. Instead, it assumes it's on the initial page.
```
Please include:
- What the current behavior is
- What the desired behavior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by amanmahajan7** [comment]
Can you check if you facing the same issue in v7 canary? I believe any odd behavior should be fixed

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md

**Comment by Ragzzy-R** [comment]
is there a fix for this in v5? its not practical for many of us to upgrade to canary. This error is still in v5.0.2

**Comment by amanmahajan7** [comment]
Closing this due to lack of activity. unfortunately old versions are no longer supported
