### ISSUE TITLE
Provide a way to select rows by row index

### ISSUE THREAD

**Issue by moodysalem** [adazzle/react-data-grid#228]
The current row selection mechanism uses a rowKey property, but if you're adding records that would not have a primary key until saving, it doesn't make much sense. Would much prefer a way to select rows by row index (maybe this could be how it works if you don't specify a rowKey property)

**Comment by bakesteve** [comment]
We moved to rowKey as rowIndex doesn’t make much sense with sorting (and in the future with groups etc)
Internally, we create pseudoKeys for new elements based on their index in the data structure with a prefix

**Comment by txm** [comment]
I'm not sure if this is related to what I need to do ...

I want to programatically select Multiple Rows http://adazzle.github.io/react-data-grid/examples.html#/multi-row-select

What object is this expecting?

  getInitialState: function() {
    return {selectedRows: []}
  },

I've tried adding isSelected: true into each row.

**Comment by moodysalem** [comment]
@txm I believe selectedRows is expecting an array of values present in the [rowKey] attribute of each of the data row objects

e.g. if you pass rowKey: 'id' to the data grid and selectedRows: [1] then the data row that has an id attribute value of 1 will be selected

IMO, I think sorting the input array should be handled entirely by the parent component, and that the data grid shouldn't need to know about the key for an object

**Comment by moodysalem** [comment]
So there's no way to unselect rows as far as I can tell, and enableRowSelect has a propType of boolean, not React.PropTypes.oneOf([true,false,'multi']) or React.PropTypes.oneOfType([React.PropTypes.bool, React.PropTypes.string])

**Comment by txm** [comment]
Thanks @moodysalem that's exactly what (I think) I am doing [sad smiley].

**Comment by txm** [comment]
Assuming we're right on the array of id's passed in, then I think it's a bug, well for my question anyway.

https://github.com/adazzle/react-data-grid/issues/232

Sorry for the thread jack.

**Comment by moodysalem** [comment]
It's actually an array of row objects. Very strange. I implemented this the other day.

**Comment by txm** [comment]
Are these pseudoKeys accessible to devs?  It's still not clear to me if
programmatically selecting Rows is broken/not implemented or if I'm doing
something wrong.

In my use case I have 2 x DataGrid's, the first contains a summary with
just a few columns and row group headers, upon selecting rows and clicking
through to the second detailed view more columns are displayed along with
the child rows.  When I click back to the first summary grid I still want
to have the original rows selected.

On 25 February 2016 at 09:56, Steven Baker <notifications@github.com> wrote:

> We moved to rowKey as rowIndex doesn’t make much sense with sorting (and
> in the future with groups etc)
> Internally, we create pseudoKeys for new elements based on their index in
> the data structure with a prefix
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adazzle/react-data-grid/issues/228#issuecomment-188698237>
> .
>



-- 
Andrew McGregor
07940 22 33 11

**Comment by malonecj** [comment]
@txm as a workaround to this issue, to programatically set the selected row I would try manually set the state of the grid like this https://github.com/adazzle/react-data-grid/issues/232#issuecomment-189363083

@moodysalem perhaps we could achieve this that if the rowGetter returns an object that has an isSelected property it would be marked as selected in the grid, and remove the responsibility of ReactDataGrid to manage selectedRows in state

**Comment by moodysalem** [comment]
@malonecj Actually I think you could probably do this today by using the addon checkbox editor (there are no examples but [here's the source file](https://github.com/adazzle/react-data-grid/blob/master/src/addons/editors/CheckboxEditor.js)) for the first column

**Comment by diogofcunha** [comment]
Hi @moodysalem.

You can do this in the current version of rdg.

You need to pass a _rowSelection shape_ saying what you want to select by and store the indexes somewhere.

Some code snippets that can help.

```

onRowsSelected(rows) {
 this.setState({selectedIndexes: this.state.selectedIndexes.concat(rows.map(r => r.rowIdx))});
}

onRowsDeselected(rows) {
   let rowIndexes = rows.map(r => r.rowIdx);
   this.setState({selectedIndexes: this.state.selectedIndexes.filter(i => rowIndexes.indexOf(i) === -1 )});
}
....
rowSelection={{
   showCheckbox: true,
   enableShiftSelect: true,
   onRowsSelected: this.onRowsSelected,
   onRowsDeselected: this.onRowsDeselected,
   selectBy: {
      indexes: this.state.selectedIndexes
   }
}
```

You can also check [this example](http://adazzle.github.io/react-data-grid/examples.html#/row-select).

Cheers

**Comment by moodysalem** [comment]
@diogofcunha It looks like sorting is now owned by the parent component (Idk if it was different when I said that it should be in one of my earlier posts). It seems like you could simplify the component to only allow selecting by indexes, and just have `selectedRows: PropTypes.arrayOf(PropTypes.number)` & `onChangeSelectedRows: PropTypes.func` props. 

Anyway, it looks like it can be done now. The only thing I don't like is `onRowsSelected(rows)` takes an array of newly selected rows, instead of just the *new* array of selected rows. Thus you need to have both `onRowsSelected` and `onRowsDeselected` instead of something like `onChangeSelectedRows`

**Comment by crossSulation** [comment]
How can I control the left checkbox status, say, set that disabled or not
