### ISSUE TITLE
bug when grid placed inside bootstrap tab or modal

### ISSUE THREAD

**Issue by shekharkul** [adazzle/react-data-grid#85]
Hi,
I am using ‘react-data-grid’ component in my application, but when component is rendered at first time it won’t get display on window and when I open developer tool bar then component is working fine.
Please let us know your opinion on the same.
 render:function(i)
    {
  var rowGetter = function(i){
            return _rows[i];
        };
 return(
My component tag is as below.
<ReactDataGrid
enableCellSelect={true}
columns={columns}
rowGetter={rowGetter}
rowsCount={_rows.length}
onRowUpdated={this.handleRowUpdated}/>
   );
}

Thanks in advance.
Regards,
Shekhar

**Comment by malonecj** [comment]
Are there any script errors available? That problem often happens when code is trying to access the ```console``` object. Are you using Internet Explorer? The console is only available after opening the developer tools. 

In react-data-grid, there is nowhere in code that is accessing the console. However, if you are using the development build of react in IE then you need to include the console polyfil

https://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills

**Comment by SerialVelocity** [comment]
Hey,

I think we're encountering the same issue. The issue is quite easily reproducible by creating a bootstrap panel which is initially closed, then add the react-data-grid to the panel.

The issue is that the width is being set incorrectly when the element is hidden and is not updated when it is visible again. Resizing the browser window also makes it visible.

**Comment by malonecj** [comment]
OK thanks. I will look at this

**Comment by shekharkul** [comment]
No there is no script error 
We are using Chrome browser for our application
i removed all console object.
but still the problem is not resolved.

Please find below sample code that i have implemented.

1) to Generate column data dinamically
  Object.keys(TreeViewDetails.Headers).map(function(Item,index){
                if(TreeViewDetails.Headers[Item].Type == 'Item')
                {   columns.push({
                        key:TreeViewDetails.Headers[Item].Name,
                        name:TreeViewDetails.Headers[Item].Name,
                        resizable : true,
                        editable : true
                    });
                }
                else if(TreeViewDetails.Headers[Item].Type == 'ID')
                {
                    columns.push({
                        key:TreeViewDetails.Headers[Item].Name,
                        name:TreeViewDetails.Headers[Item].Name,
                    });
                }
                else
                {
                    columns.push({
                        key:TreeViewDetails.Headers[Item].Name,
                        name:TreeViewDetails.Headers[Item].Name,
                        resizable : true,
                    });
                }
                           });
2. To generate row dynamically.
 var Itemarr = [];
            columnData = Object.keys(TreeViewDetails.Data[0]);
            Object.keys(TreeViewDetails.Data).map(function(Item,index){
                var result=[];
                count = 0;
                Itemarr = [];
                result[columnData[count++]] =TreeViewDetails.Data[Item].Task;
                result[columnData[count++]] = TreeViewDetails.Data[Item].TaskID;
                result[columnData[count++]] = TreeViewDetails.Data[Item].Prop1;
                result[columnData[count++]] = TreeViewDetails.Data[Item].Prop1ID;
                result[columnData[count++]] = TreeViewDetails.Data[Item].Steps;
                result[columnData[count++]] = TreeViewDetails.Data[Item].StepsID;
                _rows.push(result);
            });

3. row getter function
 var rowGetter = function(i){
            return _rows[i];
        };
4. Return statement
return(
           <ReactDataGrid
             enableCellSelect={true}
            columns={columns}
            rowGetter={_rows}
            rowsCount={_rows.length}
             minHeight={500}
            onRowUpdated={this.handleRowUpdated}/>
    );


Thanks,
Shekhar

**Comment by myranx** [comment]
I met the same issue with shekharkul,  1. when changing the columns, it displays the columns last time before change ; 2.if the column didn't set width, it is not display.      But when changing the browser's window size, the table displays correct.  By the way, the issues become if  the table placed in bootstrap's tab or modal,  otherwise, it works fine.

**Comment by bakesteve** [comment]
ok - we don't use either of those - so guessing must be some funky css
we'll take a look - though if anyone has an example with this not working, that'd be great (jsfiddle or on your fork)

**Comment by shekharkul** [comment]
The problem is  that initially column length is 0, so data is not bind properly.
so i checked column length before data bind to the grid and it is working fine.
 {columns.length>0?<ReactDataGrid
             enableCellSelect={true}
            columns={columns}
            rowGetter={rowGetter}
            rowsCount={_rows.length}
            onRowUpdated={this.handleRowUpdated}/>:null}

**Comment by cristian-neacsu** [comment]
I have the same issue, didn't find a workaround so far, still looking.

**Comment by bollabamo** [comment]
Having the same issue. I tried checking columns length beforehand, but that doesn't seem to fix it.

**Comment by pacjin79** [comment]
Hey guys, having the exact same issues here, any help would be greatly appreciated for I absolutely love react-data-grid!  I'm not sure how to do a Jfiddle for this but here's the steps to recreate.

1. Create a React Component with ReactDataGrid.
2. Stick that component within a bootstrap tab container (**Note** if the component is in the first tab and displays first, ReactDataGrid works perfect.  The issue manifests itself when ReactDataGrid is in a tab that's not initially displayed.  When the user clicks on the tab to access ReactDataGrid, he will see absolutely nothing for the width is 0 all around).  

I run into these issues a lot when using SVG canvas with bootstrap modal and tab, the root cause is usually viewport not being available at initial render to calculate proper dimensions etc. 

For those of you who need a temp work around.  I messed around with altering the width post render using Jquery to get the grid to show up. (**Note** not perfect for the columns width do not distribute evenly based on the  viewport).  Anyways, here's the snippet in case it can get you over a hump,

```
 componentDidUpdate(){
        const grid = this.refs.grid;
        const jqueryGrid = $(grid.getDOMNode());
        const reactCanvas = jqueryGrid.find('.react-grid-Canvas');
        const reactHeaderRow = jqueryGrid.find('.react-grid-HeaderRow');
        const reactGridCell = jqueryGrid.find('.react-grid-Cell');
        console.log("in get update canvas width = "+jqueryGrid.parent().width());
        if(jqueryGrid.width() == 0){
            const tabContainerWidth = jqueryGrid.closest('div.tab-content').width();
            jqueryGrid.width(tabContainerWidth);
            reactCanvas.width(tabContainerWidth);
            reactHeaderRow.width(tabContainerWidth);
            reactGridCell.width(tabContainerWidth);
            console.log("after set get update canvas width = "+reactCanvas.width());
        }
    }
```
A permanent fix would be greatly appreciated, thanks again for this great library/

**Comment by pacjin79** [comment]
Looking through the source code seems there's a minWidth attribute on ReactDataGrid that will allow users to set a fixed width manually and that seems to have solved the problem for now!

**Comment by kriscarle** [comment]
Another hack that works for me is to fire a resize event when the tab is clicked for the first time

`onTabClick(){
    window.dispatchEvent(new Event('resize'));
  },`
then
`<li className="tab col s4"><a href="#data" onClick={this.onTabClick}>Data</li>`

It looks like there is code that tries to handle this case here: https://github.com/adazzle/react-data-grid/blob/2bf57ccf32509c8f0ff8aebd61722373eebe6dc9/src/addons/grids/ReactDataGrid.js#L528
but it doesn't handle the case where parent.offsetWidth is 0 and not undefined or NaN. I think the solution is just to set the width to 100% if the detected width is zero. I'll submit a PR for that.

**Comment by malonecj** [comment]
fixed by https://github.com/adazzle/react-data-grid/pull/263

**Comment by nvarchar** [comment]
I'm still seeing this issue when using react bootstrap tabs. I'd like the columns to fill the width of the container and a grid that is showing on load does this fine. However, hidden data grids do not calculate totalWidth correctly and set their columns to the minimum width (80px). I have three columns, so I tried setting their width to a percentage with {key: "id", name: "ID", width: "33%"} but this also does not work.
